import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import CryptoProvider from "@/components/crypto-provider";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`font-mono antialiased`}
			>
				<CryptoProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						disableTransitionOnChange
					>
						<Header />
						<main>
							{children}
						</main>
					</ThemeProvider>
				</CryptoProvider>
			</body>
		</html>
	);
}
